export const db2 = [
  {
    id: 1,
    name: {
      macroproceso: "Macroproceso2",
      proceso: "Proceso",
    },
    stages: {
      recInformacion: "en curso",
      modelado: "finalizado",
      atrProcesos: "Pendiente",
      atrTareas: "Pendiente",
      fad: "Pendiente",
      keyUser: "En curso",
      coordProcesos: "En curso",
      validacionEdison: "Pendiente",
      statusGeneral: "En curso",
    },
    detalle: {
      respSeguimiento: "Laura",
      keyUser: "Pablo",
      observaciones: "Detalles del proceso",
    },
  },
  {
    id: 2,
    name: {
      macroproceso: "Macroproceso2",
      proceso: "Proceso",
    },
    stages: {
      recInformacion: "en curso",
      modelado: "finalizado",
      atrProcesos: "Pendiente",
      atrTareas: "Pendiente",
      fad: "Pendiente",
      keyUser: "En curso",
      coordProcesos: "En curso",
      validacionEdison: "Pendiente",
      statusGeneral: "En curso",
    },
    detalle: {
      respSeguimiento: "Laura",
      keyUser: "Pablo",
      observaciones: "Detalles del proceso",
    },
  },
  {
    id: 3,
    name: {
      macroproceso: "Macroproceso2",
      proceso: "Proceso",
    },
    stages: {
      recInformacion: "en curso",
      modelado: "finalizado",
      atrProcesos: "Pendiente",
      atrTareas: "Pendiente",
      fad: "Pendiente",
      keyUser: "En curso",
      coordProcesos: "En curso",
      validacionEdison: "Pendiente",
      statusGeneral: "En curso",
    },
    detalle: {
      respSeguimiento: "Laura",
      keyUser: "Pablo",
      observaciones: "Detalles del proceso",
    },
  },
  {
    id: 4,
    name: {
      macroproceso: "Macroproceso2",
      proceso: "Proceso",
    },
    stages: {
      recInformacion: "en curso",
      modelado: "finalizado",
      atrProcesos: "Pendiente",
      atrTareas: "Pendiente",
      fad: "Pendiente",
      keyUser: "En curso",
      coordProcesos: "En curso",
      validacionEdison: "Pendiente",
      statusGeneral: "En curso",
    },
    detalle: {
      respSeguimiento: "Laura",
      keyUser: "Pablo",
      observaciones: "Detalles del proceso",
    },
  },
  {
    id: 5,
    name: {
      macroproceso: "Macroproceso2",
      proceso: "Proceso",
    },
    stages: {
      recInformacion: "en curso",
      modelado: "finalizado",
      atrProcesos: "Pendiente",
      atrTareas: "Pendiente",
      fad: "Pendiente",
      keyUser: "En curso",
      coordProcesos: "En curso",
      validacionEdison: "Pendiente",
      statusGeneral: "En curso",
    },
    detalle: {
      respSeguimiento: "Laura",
      keyUser: "Pablo",
      observaciones: "Detalles del proceso",
    },
  },
  {
    id: 6,
    name: {
      macroproceso: "Macroproceso2",
      proceso: "Proceso",
    },
    stages: {
      recInformacion: "en curso",
      modelado: "finalizado",
      atrProcesos: "Pendiente",
      atrTareas: "Pendiente",
      fad: "Pendiente",
      keyUser: "En curso",
      coordProcesos: "En curso",
      validacionEdison: "Pendiente",
      statusGeneral: "En curso",
    },
    detalle: {
      respSeguimiento: "Laura",
      keyUser: "Pablo",
      observaciones: "Detalles del proceso",
    },
  },
];
