export const db = [
  {
    macroproceso: "Macroproceso",
    proceso: "Proceso",
    recInformacion: "en curso",
    modelado: "finalizado",
    atrProcesos: "Pendiente",
    atrTareas: "Pendiente",
    fad: "Pendiente",
    validacion: {
      validacionTGS: {
        keyUser: "En curso",
        coordProcesos: "En curso",
      },
      validacionEdison: "Pendiente",
    },
    statusGeneral: "En curso",
    respSeguimiento: "Laura",
    keyUser: "Pablo",
    observaciones: "Detalles del proceso",
  },
  {
    macroproceso: "Macroproceso",
    proceso: "Proceso",
    recInformacion: "en curso",
    modelado: "finalizado",
    atrProcesos: "Pendiente",
    atrTareas: "Pendiente",
    fad: "Pendiente",
    validacion: {
      validacionTGS: {
        keyUser: "En curso",
        coordProcesos: "En curso",
      },
      validacionEdison: "Pendiente",
    },
    statusGeneral: "En curso",
    respSeguimiento: "Laura",
    keyUser: "Pablo",
    observaciones: "Detalles del proceso",
  },
  {
    macroproceso: "Macroproceso",
    proceso: "Proceso",
    recInformacion: "en curso",
    modelado: "finalizado",
    atrProcesos: "Pendiente",
    atrTareas: "Pendiente",
    fad: "Pendiente",
    validacion: {
      validacionTGS: {
        keyUser: "En curso",
        coordProcesos: "En curso",
      },
      validacionEdison: "Pendiente",
    },
    statusGeneral: "En curso",
    respSeguimiento: "Laura",
    keyUser: "Pablo",
    observaciones: "Detalles del proceso",
  },
  {
    macroproceso: "Macroproceso",
    proceso: "Proceso",
    recInformacion: "en curso",
    modelado: "finalizado",
    atrProcesos: "Pendiente",
    atrTareas: "Pendiente",
    fad: "Pendiente",
    validacion: {
      validacionTGS: {
        keyUser: "En curso",
        coordProcesos: "En curso",
      },
      validacionEdison: "Pendiente",
    },
    statusGeneral: "En curso",
    respSeguimiento: "Laura",
    keyUser: "Pablo",
    observaciones: "Detalles del proceso",
  },
  {
    macroproceso: "Macroproceso",
    proceso: "Proceso",
    recInformacion: "en curso",
    modelado: "finalizado",
    atrProcesos: "Pendiente",
    atrTareas: "Pendiente",
    fad: "Pendiente",
    validacion: {
      validacionTGS: {
        keyUser: "En curso",
        coordProcesos: "En curso",
      },
      validacionEdison: "Pendiente",
    },
    statusGeneral: "En curso",
    respSeguimiento: "Laura",
    keyUser: "Pablo",
    observaciones: "Detalles del proceso",
  },
  {
    macroproceso: "Macroproceso",
    proceso: "Proceso",
    recInformacion: "en curso",
    modelado: "finalizado",
    atrProcesos: "Pendiente",
    atrTareas: "Pendiente",
    fad: "Pendiente",
    validacion: {
      validacionTGS: {
        keyUser: "En curso",
        coordProcesos: "En curso",
      },
      validacionEdison: "Pendiente",
    },
    statusGeneral: "En curso",
    respSeguimiento: "Laura",
    keyUser: "Pablo",
    observaciones: "Detalles del proceso",
  },
];
